const projects = [
	{
		title: "Document Library",
		date: "Aug 2025",
		timestamp: "2025-08-10T00:00:00Z",
		github: "https://github.com/Wartets/Wartets/lib",
		description: "Interactive digital library for academic notes and papers. Features a custom PDF viewer, real-time search, and dynamic filtering.",
		longDescrition: "A comprehensive digital archive designed to organize and present academic notes, research papers, and personal documents. The application features a custom-built PDF viewer with lazy loading and preview generation, ensuring a seamless reading experience directly in the browser. It incorporates advanced filtering, sorting, and fuzzy search capabilities to efficiently navigate through categories like Physics, Mathematics, and Computer Science. ",
		icon: "../img/Document-Library-card.png",
		image: "img/Document-Library-card.png",
		link: "https://wartets.github.io/Wartets/lib/library.html",
		keywords: ["tool", "interactive", "educational", "physics", "math", "visualization"],
		show: true
	},
	{
		title: "N-Body-Simulation",
		date: "Jan 2026",
		timestamp: "2026-01-01T08:00:00Z",
		github: "https://github.com/wartets/N-Body-Simulation",
		description: "An advanced physics sandbox for simulating N-body systems with gravity, electromagnetism, and collisions. Features extensive tools for creating, modifying, and analyzing complex cosmic scenarios in real-time.",
		longDescrition: "An advanced physics sandbox for simulating N-body systems under various physical laws. This feature-rich simulation allows users to model gravitational, electric, and magnetic interactions with high precision. It incorporates a Barnes-Hut algorithm for efficient long-range force calculation, enabling large-scale simulations. The engine supports elastic bonds, solid barriers, and various environmental zones like viscosity, thermal, and custom force fields. Advanced features include body fragmentation, thermodynamic properties, and a complete undo/redo history for all actions. The highly interactive interface provides real-time control over every simulation parameter, body property, and environmental effect, making it a powerful tool for both educational exploration and complex cosmic experimentation.",
		icon: "../img/N-Body-Simulation-card.png",
		image: "img/N-Body-Simulation-card.png",
		link: "https://wartets.github.io/N-Body-Simulation/",
		keywords: ["simulation", "physics", "n-body", "interactive", "visualization", "sandbox"],
		show: true
	},
	{
		title: "FDTD Wave Simulator",
		date: "Dec 2025",
		timestamp: "2025-12-01T08:00:01Z",
		github: "https://github.com/wartets/FDTD-Wave-Simulator",
		description: "A web-based simulator for 2D wave propagation using the FDTD method. Visualize phenomena like interference and reflection with interactive tools for sources, obstacles, and boundary conditions.",
		longDescrition: "This project is a high-performance numerical simulator that models and visualizes 2D scalar wave propagation using the Finite-Difference Time-Domain (FDTD) method. The application features a client-server architecture where a powerful Python backend (using Flask and SocketIO) handles the complex physics calculations, while a responsive JavaScript frontend provides real-time visualization and an interactive user interface. Users can explore wave phenomena like interference, reflection, and diffraction by drawing wave sources and obstacles directly onto the grid. The simulation is highly configurable, offering control over grid dimensions, wave speed, and various boundary conditions—including fixed (Dirichlet), periodic, reflecting (Neumann), and absorbing (Mur). The dynamic visualization uses a selectable colormap that can be normalized in real-time, providing a clear and intuitive representation of wave amplitude. It serves as an excellent educational tool for students and enthusiasts to explore the principles of wave physics.",
		icon: "../img/FDTD-Wave-Simulator-card.png",
		image: "img/FDTD-Wave-Simulator-card.png",
		link: "https://wartets.github.io/FDTD-Wave-Simulator/",
		keywords: ["simulation", "physics", "visualization", "interactive", "educational", "python"],
		show: true
	},
	{
		title: "Origami",
		date: "Nov 2025",
		timestamp: "2025-11-01T08:00:00Z",
		github: "https://github.com/wartets/Origami",
		description: "An interactive web-based origami simulator to explore the mathematical axioms of paper folding. Create complex crease patterns, experiment with folds, and visualize the geometric principles behind the art of origami.",
		longDescrition: `Origami is an advanced, interactive web-based simulator dedicated to exploring the mathematical principles of paper folding. The application provides a comprehensive toolset based on the seven Huzita-Hatori axioms, allowing users to construct complex crease patterns with geometric precision. Users create folds by selecting points and edges on virtual paper, with real-time visual feedback that includes construction lines and a preview of the resulting crease. The simulation engine accurately handles face splitting, vertex reflection, and the complex layering of paper that results from each fold. It also includes an undo/redo history, state persistence, an X-ray mode to see hidden layers, and the ability to import standard Crease Pattern (.cp) files. This project is both an educational tool for learning geometric constructions and a creative sandbox for origami enthusiasts and mathematicians.`,
		icon: "../img/Origami-card.png",
		image: "img/Origami-card.png",
		link: "https://wartets.github.io/Origami/",
		keywords: ["simulation", "math", "art", "tool", "interactive", "educational"],
		show: true
	},
	{
		title: "Molecule Builder",
		date: "Oct 2025",
		timestamp: "2025-10-18T20:07:00Z",
		github: "https://github.com/wartets/Molecule-Builder",
		description: "Interactive web-based tool that allows you to create, visualize, and manipulate 3D models of chemical molecules.",
		longDescrition: `This interactive web-based tool allows users to build, visualize, and manipulate 3D models of chemical molecules. With a user-friendly interface, you can add atoms, create and increment bonds, and view molecular representations such as the Van der Waals surface. The tool provides important information through features like the display of lone pairs and formal charges, which are essential for understanding chemical structures and reactivity. Users can manipulate the view by rotating, panning, and zooming, and they can move or delete atoms. This simulation focuses on providing a flexible and intuitive way to explore molecular geometry, making it a valuable educational resource for students and a useful tool for chemistry enthusiasts.`,
		icon: "../img/Molecule-Builder-card.png",
		image: "img/Molecule-Builder-card.png",
		link: "https://wartets.github.io/Molecule-Builder/",
		keywords: ["simulation", "chemistry", "3d", "visualization", "interactive", "educational"],
		show: true
	},
	{
		title: "Computational Chemistry",
		date: "Oct 2025",
		timestamp: "2025-10-12T20:07:00Z",
		github: "https://github.com/wartets/ComputationalChemistry",
		description: "This website is an interactive tool to explore molecular geometry.It shows how atoms and electrons arrange through simple forces like attraction and repulsion.",
		longDescrition: `This website offers an interactive tool to explore molecular geometry by showing how atoms in a molecule arrange themselves based on fundamental forces like attraction and repulsion. Users can select from various pre-configured molecules, such as H₂O, CH₄, and CO₂, or even create their own custom molecules. The simulation visualizes electron clouds as a particle system, where thousands of particles are influenced by nuclei. Key simulation parameters—such as particle density, quantum constants, and repulsion forces—are adjustable, allowing users to observe how these changes impact the molecular structure. This tool provides an educational and interactive experience by illustrating how these fundamental principles determine molecular shape.`,
		icon: "../img/ComputationalChemistry-card.png",
		image: "img/ComputationalChemistry-card.png",
		link: "https://wartets.github.io/ComputationalChemistry/",
		keywords: ["simulation", "chemistry", "physics", "visualization", "interactive", "educational"],
		show: true
	},
	{
		title: "Match 3",
		date: "Sept 2025",
		timestamp: "2025-09-04T08:00:00Z",
		github: "https://github.com/wartets/Match3",
		description: "A classic gem-matching puzzle game with smooth animations and swap mechanics. Create lines of three or more matching colors to score points in this implementation.",
		longDescrition: `A classic gem-matching puzzle game with smooth animations and swap mechanics. Create lines of three or more matching colors to score points in this implementation. This project delivers a traditional Match 3 game experience with polished visual and interactive elements.`,
		icon: "../img/Match3-card.png",
		image: "img/Match3-card.png",
		link: "https://wartets.github.io/Match3/",
		keywords: ["game", "puzzle", "match-3"],
		show: true
	},
	{
		title: "Labyrinthe",
		date: "Aug 2025",
		timestamp: "2025-08-19T08:00:00Z",
		github: "https://github.com/wartets/Labyrinthe",
		description: "This project explores maze solving through a highly customizable genetic/evolutionary algorithm approach. (fr)",
		longDescrition: `This project explores maze solving through a highly customizable genetic and evolutionary algorithm. It allows users to generate mazes using various algorithms—including DFS, Prim's, and Kruskal's—and provides precise control over labyrinth generation with parameters like maze size and opening percentages. The core of the project is the genetic algorithm used to find the solution, which can be fine-tuned with settings for population size, mutation rate, and elitism rate. The fitness function that guides the evolution of the solutions is also highly configurable, with weights for path length, distance to the exit and penalties for collisions. Advanced features, such as multiple crossover and mutation types, ensure a deep and adaptable maze-solving simulation. The project is an ideal platform for visualizing and understanding evolutionary computation in action.`,
		icon: "../img/Labyrinthe-card.png",
		image: "img/Labyrinthe-card.png",
		link: "https://wartets.github.io/Labyrinthe/",
		keywords: ["simulation", "ai", "genetic-algorithm", "pathfinding", "maze"],
		show: true
	},
	{
		title: "Autoroutes",
		date: "Aug 2025",
		timestamp: "2025-08-13T08:00:00Z",
		github: "https://github.com/wartets/Autoroutes",
		description: "A web simulation that procedurally generates a highway system. It uses simple rules to create a complex, winding road network, showcasing how basic algorithms can lead to intricate, emergent patterns. (fr)",
		longDescrition: `A web simulation that procedurally generates a highway system. It uses simple rules to create a complex, winding road network, showcasing how basic algorithms can lead to intricate, emergent patterns. This project serves as a clear and pedagogical tool for visualizing emergent complexity.`,
		icon: "../img/Autoroutes-card.png",
		image: "img/Autoroutes-card.png",
		link: "https://wartets.github.io/Autoroutes/",
		keywords: ["simulation", "procedural-generation", "visualization", "emergence"],
		show: true
	},
	{
		title: "Mercury-Redstone",
		date: "Jul 2025",
		timestamp: "2025-07-07T08:00:00Z",
		github: "https://github.com/wartets/Mercury",
		description: "Simulation of the May 5, 1961 Mercury-Redstone mission. (fr)",
		longDescrition: `This project is a detailed simulation of the May 5, 1961 Mercury-Redstone mission, known as Freedom 7, which was the first American human spaceflight, piloted by astronaut Alan Shepard. The simulation displays key flight data, including altitude, speed, and g-force, and plots the flight's trajectory and acceleration profile in real time. Mission objectives—such as testing the capsule's systems, manual controls, and heat shield, as well as studying the effects of weightlessness—are central to this interactive experience. The simulation is based on the actual stats of the mission, which achieved an altitude of 187 km.`,
		icon: "../img/Mercury-card.png",
		image: "img/Mercury-card.png",
		link: "https://wartets.github.io/Mercury/",
		keywords: ["simulation", "physics", "space", "historical", "interactive"],
		show: true
	},
	{
		title: "Caustiques",
		date: "Jul 2025",
		timestamp: "2025-07-08T08:00:00Z",
		github: "https://github.com/wartets/Caustiques",
		description: "Simulation of caustic lines due to refraction of a corrugated glass base. (fr)",
		longDescrition: `This project is an interactive optical simulation that visualizes caustic lines formed by the refraction of light through a corrugated glass base. Users have fine-grained control over the simulation parameters and can adjust the cup's dimensions (height and radius), the light source's properties (height, angle, and position), and the glass orientation (X and Y tilt). The simulation accurately traces the path of thousands of light rays, and users can set the maximum number of reflections for each ray, providing a powerful tool to explore the intricate and beautiful patterns that emerge.`,
		icon: "../img/Caustiques-card.png",
		image: "img/Caustiques-card.png",
		link: "https://wartets.github.io/Caustiques/",
		keywords: ["simulation", "physics", "optics", "visualization", "interactive"],
		show: true
	},
	{
		title: "Fractals",
		date: "Jul 2025",
		timestamp: "2025-07-11T08:00:00Z",
		github: "https://github.com/wartets/Fractals",
		description: "Generating fractal plant structures with affine transformations. (fr)",
		longDescrition: `This project showcases the generation of a wide variety of fractal plant structures using affine transformations. Fractals, known for their self-similarity and repeating patterns at different scales, are visualized here with several selectable types, including 'Fern,' 'Tree,' and 'Dragon' fractals. The web interface offers a high degree of control over the generation with parameters to define the quality and to reset the generation or the view. For analytical purposes, the program can compute the fractal dimension of a generated shape. These features allow you to create complex and visually appealing digital images from simple mathematical formulas and explore those fascinating mathematical objects.`,
		icon: "../img/Fractals-card.png",
		image: "img/Fractals-card.png",
		link: "https://wartets.github.io/Fractals/",
		keywords: ["generative-art", "math", "fractals", "visualization", "L-system"],
		show: true
	},
	{
		title: "Lenia Web",
		date: "Jul 2025",
		timestamp: "2025-07-01T08:00:00Z",
		github: "https://github.com/wartets/Lenia-Web",
		description: "A dynamic web implementation of the Lenia system, modeling artificial organisms evolving via parameterized growth fields.",
		longDescrition: `A dynamic web implementation of the Lenia system, a continuous cellular automaton that is also a generalization of Conway’s Game of Life. This web implementation can create a diverse range of complex and highly life-like patterns by modeling artificial organisms evolving in a world defined by parameterized growth fields. This generalization from a discrete to a continuous domain is what allows for the incredible visual diversity, providing a world of smooth transitions and endless complexity for the digital organisms it spawns. Users can choose from plenty of initial configurations and fine-tune the grid parameters to explore and generate their own creatures.`,
		icon: "../img/LeniaWeb-card.png",
		image: "img/LeniaWeb-card.png",
		link: "https://wartets.github.io/Lenia-Web/",
		keywords: ["simulation", "ai", "cellular-automata", "emergence", "python"],
		show: true
	},
	{
		title: "Curve Fitting",
		date: "Jun 2025",
		timestamp: "2025-06-01T08:00:00Z",
		github: "https://github.com/wartets/Curve-Fitting",
		description: "This project illustrates thin-plate splines, a smooth surface interpolation technique used in geometry and machine learning.",
		longDescrition: `This project is a powerful interactive illustration of the thin-plate splines technique, a method for generating a smooth surface from a set of data points widely used in geometric modeling and machine learning. In this tool, you can directly add points to the canvas and instantaneously visualize how the spline adapts to new data. It is possible to adjust a λ (lambda) parameter, which controls the algorithm's trade-off between interpolation and linear regression, allowing you to choose on a spectrum from a fluctuating curve that passes through all points to a smoother line. "Curve Fitting" lets you explore this interpolation and smoothing in an interactive way.`,
		icon: "../img/Curve-Fitting-card.png",
		image: "img/Curve-Fitting-card.png",
		link: "https://wartets.github.io/Curve-Fitting/",
		keywords: ["math", "visualization", "tool", "interactive", "interpolation"],
		show: false
	},
	{
		title: "Procedural Art Gen.",
		date: "May 2025",
		timestamp: "2025-05-01T08:00:00Z",
		github: "https://github.com/wartets/Procedural-Art",
		description: "A seed-based generative art system creating unique visual patterns. Explore geometric formations, organic fractals, and abstract compositions that remain reproducible.",
		longDescrition: `A robust seed-based generative art system built to produce a vast diversity of unique visual patterns. The ‘Seed’ and ‘Complexity’ sliders, along with the ‘Pattern’ and ‘Palettes’ dropdowns in its user-friendly interface, encourage the exploration of a wide range of styles—from geometric formations and organic fractals to abstract compositions. All of this is accomplished while guaranteeing that you can find your amazing creations again with their seed alone. Through this intuitive setup, the tool demonstrates how simple, repeatable algorithms can generate aesthetic diversity.`,
		icon: "../img/Procedural-Art-card.png",
		image: "img/Procedural-Art-card.png",
		link: "https://wartets.github.io/Procedural-Art/",
		keywords: ["generative-art", "art", "procedural-generation", "creative-coding", "fractals"],
		show: true
	},
	[
		{
			title: "Space Trip Game 3D",
			date: "Apr 2025",
			timestamp: "2025-04-01T08:00:00Z",
			github: "https://github.com/wartets/Space-Trip-3D",
			description: "Survival game for a small ship in a swarm of asteroids, where you have to score as many points as possible by destroying them and staying alive as long as possible.",
			longDescrition: `A fast-paced, single-player 3D survival game where you pilot a small ship stuck in a dense and hostile asteroid field. You must use skill, luck, and dexterity to keep your ship unscathed for as long as possible. A high-score system motivates players to compete and test their mettle. The main focus of this project is to test spatial navigation and fast-paced combat in various environmental settings, all made possible through a web-friendly canvas for everyone to play and enjoy for a bit of entertainment.`,
			icon: "../img/Spaceship-card.png",
			image: "img/Spaceship-card.png",
			link: "https://wartets.github.io/Space-Trip-3D/",
			keywords: ["game", "3d", "space", "survival", "arcade", "three.js"],
			show: true
		},
		{
			title: "Space Trip Game 2D",
			date: "Mar 2025",
			timestamp: "2025-03-01T08:00:00Z",
			github: "https://github.com/wartets/Space-Trip-2D",
			description: "\"Simplified\" 2D version of the Space Trip game.",
			longDescrition: `This is the simplified 2D version of its 3D counterpart, but it's also a game in its own right. The experience is an asteroid-scoring survival action game that challenges players to test their skills in different game modes where only reflexes matter. How long you can dodge can change everything. This more arcade-style version of a space survival game promises a fair dose of instant gaming fun, with space-themed backgrounds and other features that will surely entertain.`,
			icon: "../img/Space-Trip-2D.png",
			image: "img/Space-Trip-2D.png",
			link: "https://wartets.github.io/Space-Trip-2D/",
			keywords: ["game", "2d", "space", "survival", "arcade"],
			show: true
		}
	],
	{
		title: "Sudoku",
		date: "Feb 2025",
		timestamp: "2025-02-01T08:00:00Z",
		github: "https://github.com/wartets/Sudoku",
		description: "A customizable web-based Sudoku game that allows you to adjust both the grid size and difficulty level. It features real-time input validation, providing an interactive and engaging puzzle-solving experience.",
		longDescrition: `A customizable web-based implementation of Sudoku, the classic logic puzzle game. It allows the player to set their own custom rules, such as the difficulty level, and supports a wide range of grid dimensions, which is always an enjoyable feature in this type of classic game. Overall, this is a strong web-game that offers tons of replayability that never goes out of style.`,
		icon: "../img/Sudoku-card.png",
		image: "img/Sudoku-card.png",
		link: "https://wartets.github.io/Sudoku/",
		keywords: ["game", "puzzle", "logic", "sudoku"],
		show: true
	},
	{
		title: "Chess Game",
		date: "Jan 2025",
		timestamp: "2025-01-01T08:00:00Z",
		github: "https://github.com/wartets/Chess-Game",
		description: "An Interactive chess game, offering classic and random board setups. It allows custom piece placement, and personalized size grid.",
		longDescrition: `An interactive chess game offering classic and random board setups. It allows custom piece placement and personalized grid size. The project implements the classic game of chess, allowing two players to compete with various customizable options. It’s a tool that lets players of all levels sharpen their skills, especially with new variations that custom board sizes can provide.`,
		icon: "../img/Chess-card.png",
		image: "img/Chess-card.png",
		link: "https://wartets.github.io/Chess-Game/",
		keywords: ["game", "puzzle", "strategy", "chess"],
		show: true
	},
	{
		title: "Minesweeper",
		date: "Dec 2024",
		timestamp: "2024-12-01T08:00:00Z",
		github: "https://github.com/wartets/Demineur",
		description: "A simple mine-clearing game in javascript. Discover all the squares without touching a mine! Adjust the grid size and number of mines to personalize the experience.",
		longDescrition: `A classic implementation of Minesweeper, a logic puzzle game where you must clear a board without detonating hidden mines. This version allows players to adjust the grid dimensions and the number of mines to personalize their game. The project aims to provide a high-quality, classic, and intuitive single-player experience for anyone looking for a quick and fun mental exercise.`,
		icon: "../img/Demineur-card.png",
		image: "img/Demineur-card.png",
		link: "https://wartets.github.io/Demineur/",
		keywords: ["game", "puzzle", "logic", "minesweeper"],
		show: true
	},
	{
		title: "Julia-Set",
		date: "Nov 2024",
		timestamp: "2024-11-01T12:00:00Z",
		github: "https://github.com/wartets/Julia-Set",
		description: "Explore the beauty of Julia sets with interactive controls to adjust equations and rendering settings. Create custom stunning fractal visuals in \"real-time\" with a simple interface.",
		longDescrition: `This project lets you explore the abyssal beauty of fractals generated from complex numbers. It uses core mathematical laws, such as function composition, to generate a near-infinite variety of aesthetic shapes through a simple graphical interface. Its fine-grained controls over initial mathematical settings offer users a high-dimensional space of possibilities, where each unique set of parameters produces a distinct mathematical structure. The near real-time generation in the canvas gives the feeling of exploring an infinite space of possibilities within its minimalist design.`,
		icon: "../img/JuilaSet-card.png",
		image: "img/JuilaSet-card.png",
		link: "https://wartets.github.io/Julia-Set/",
		keywords: ["visualization", "math", "fractals", "interactive", "generative-art"],
		show: true
	},
	{
		title: "Bird-cloud",
		date: "Nov 2024",
		timestamp: "2024-11-01T08:00:00Z",
		github: "https://github.com/wartets/Bird-cloud",
		description: "An interactive simulation of flocking behavior in birds, based on the Boids model. Adjust parameters like speed, vision radius, and randomness to see how individual rules create collective patterns.",
		longDescrition: `This dynamic agent-based simulation lets you discover the beauty of emergent complexity through a toy model of artificial life. It reproduces the collective flocking behavior of birds or schooling of fish using a population of thousands of separate, autonomous 'boid' entities. At its core, it uses classic AI behavior algorithms like Reynolds' Boids model. The simulation results can be adjusted with basic flight parameters and a full array of custom variables, allowing you to have fun trying all possible flight behaviors. It’s a classic and excellent example of an agent-based system.`,
		icon: "../img/BirdCloud-card.png",
		image: "img/BirdCloud-card.png",
		link: "https://wartets.github.io/Bird-cloud/",
		keywords: ["simulation", "ai", "emergence", "boids", "interactive"],
		show: true
	},
	{
		title: "N-Body-Problem",
		date: "Oct 2024",
		timestamp: "2024-10-01T08:00:00Z",
		github: "https://github.com/wartets/N-Body-Problem",
		description: "A physics simulation of an N-body system with gravity, collisions, and electromagnetism. Customize object properties like mass, charge, and position to observe how forces shape their motion.",
		longDescrition: `A physics simulation of an N-body system with gravity, collisions, and electromagnetism. This classic problem in physics involves predicting the individual motions of a group of celestial objects interacting with each other gravitationally. This tool allows you to customize object properties like mass, charge, and position to observe how forces shape their motion. It provides an intuitive glimpse into the unique and chaotic dynamics that complex multi-body systems produce.`,
		icon: "../img/NBodyProblem-card.png",
		image: "img/NBodyProblem-card.png",
		link: "https://wartets.github.io/N-Body-Problem/",
		keywords: ["simulation", "physics", "n-body", "interactive", "educational"],
		show: true
	},
	{
		title: "Lenia-Simulation",
		date: "Jun 2024",
		timestamp: "2024-06-01T08:00:00Z",
		github: "https://github.com/wartets/Lenia-Simulation",
		description: "Discover Lenia, a continuous cellular automaton that extends Conway's Game of Life. Explore lifelike, emergent patterns in a world of smooth transitions and endless complexity.",
		longDescrition: `Discover Lenia, a continuous cellular automaton that extends Conway's Game of Life. Explore lifelike, emergent patterns in a world of smooth transitions and endless complexity. Lenia models artificial organisms evolving via parameterized growth fields, showcasing how simple rules can lead to complex systems that grow, evolve, and develop behaviors reminiscent of real-world organisms. It's a fantastic tool for anyone with scientific curiosity about complex systems and emergence.`,
		icon: "../img/LeniaSimulation-card.png",
		image: "img/LeniaSimulation-card.png",
		link: "https://wartets.github.io/Lenia-Simulation/",
		keywords: ["simulation", "ai", "cellular-automata", "emergence", "python"],
		show: true
	},
	{
		title: "Solar-System",
		date: "May 2023",
		timestamp: "2024-05-01T08:00:00Z",
		github: "https://github.com/wartets/SolarSystem",
		description: "A 3D solar system visualization. Interact with the planets and their orbits in a dynamic and immersive interface.",
		longDescrition: `A 3D solar system visualization created to simulate our universe and its beautiful objects on various scales. It offers an immersive and informative interface where you can roam freely, visit planets and their satellites, and compare their characteristics. The goal is to allow users of any background, especially younger learners, to learn from interacting with the environment and its features.`,
		icon: "../img/SolarSystem-card.png",
		image: "img/SolarSystem-card.png",
		link: "https://wartets.github.io/SolarSystem/",
		keywords: ["visualization", "3d", "space", "simulation", "educational", "geogebra"],
		show: true
	},
	[
		{
			title: "My Music (SoundCloud)",
			date: "",
			timestamp: "",
			github: "",
			description: "I create electronic, ambient, funky, and drumcore music. I focus on improving my skills and exploring new sounds. Check out my tracks and enjoy the beats!",
			longDescrition: "I create electronic, ambient, funky, and drumcore music. I focus on improving my skills and exploring new sounds. Check out my tracks and enjoy the beats!",
			icon: "../img/Soundcloud-card.jpg",
			image: "img/Soundcloud-card.jpg",
			link: "https://soundcloud.com/wartets",
			keywords: ["music", "creative", "electronic", "ambient"],
			show: true
		},
		{
			title: "My Music (YouTube)",
			date: "",
			timestamp: "",
			github: "",
			description: "Explore my music projects on YouTube.",
			longDescrition: "Explore my music projects on YouTube.",
			icon: "../img/Soundcloud-card.jpg",
			image: "img/Soundcloud-card.jpg",
			link: "https://www.youtube.com/@Wartets",
			keywords: ["music", "creative", "electronic", "youtube"],
			show: true
		}
	]
];