const projects = [
	{
		title: "Origami",
		date: "Nov 2025",
		timestamp: "2025-11-01T08:00:00Z",
		github: "https://github.com/wartets/Origami",
		description: "An interactive web-based origami simulator to explore the mathematical axioms of paper folding. Create complex crease patterns, experiment with folds, and visualize the geometric principles behind the art of origami.",
		longDescrition: "Origami is an advanced, interactive web-based simulator dedicated to exploring the mathematical principles of paper folding. The application provides a comprehensive toolset based on the seven Huzita-Hatori axioms, allowing users to construct complex crease patterns with geometric precision. Users can select points and edges on the virtual paper to define folds, with real-time visual feedback including construction lines and a preview of the resulting crease. The simulation engine accurately handles the splitting of faces, the reflection of vertices, and the complex layering of the paper that results from each fold. It also includes features like an undo/redo history, state persistence, an X-ray mode to view hidden layers, and the ability to import standard Crease Pattern (.cp) files. This project serves as both an educational tool for learning geometric constructions and a creative sandbox for origami enthusiasts and mathematicians.",
		icon: "../img/Origami-card.png",
		image: "img/Origami-card.png",
		link: "https://wartets.github.io/Origami/",
		keywords: ["origami", "paper folding", "simulator", "interactive", "huzita-hatori axioms", "geometry", "crease pattern", "mathematical art", "visualization", "computational geometry", "educational", "javascript", "html", "css", "svg"],
		show: true
	},
	{
		title: "Molecule Builder",
		date: "Oct 2025",
		timestamp: "2025-10-18T20:07:00Z",
		github: "https://github.com/wartets/Molecule-Builder",
		description: "Interactive web-based tool that allows you to create, visualize, and manipulate 3D models of chemical molecules.",
		longDescrition: "This interactive web-based tool allows users to create, visualize, and manipulate 3D models of chemical molecules. The simulation focuses on how atoms and electrons arrange themselves based on simple forces like attraction and repulsion, offering an educational and engaging way to explore molecular geometry.",
		icon: "../img/Molecule-Builder-card.png",
		image: "img/Molecule-Builder-card.png",
		link: "https://wartets.github.io/Molecule-Builder/",
		keywords: ["chemistry", "simulation", "javascript", "css", "html", "molecular", "visualization", "educational", "interactive", "computational", "science", "atoms", "electrons", "bonds", "geometry", "molecule"],
		show: true
	},
	{
		title: "Computational Chemistry",
		date: "Oct 2025",
		timestamp: "2025-10-12T20:07:00Z",
		github: "https://github.com/wartets/ComputationalChemistry",
		description: "This website is an interactive tool to explore molecular geometry.It shows how atoms and electrons arrange through simple forces like attraction and repulsion.",
		longDescrition: "This website is an interactive tool to explore molecular geometry. It shows how atoms and electrons arrange through simple forces like attraction and repulsion. This tool helps visualize how these fundamental forces influence the structure of molecules, providing an educational and interactive experience.",
		icon: "../img/ComputationalChemistry-card.png",
		image: "img/ComputationalChemistry-card.png",
		link: "https://wartets.github.io/ComputationalChemistry/",
		keywords: ["chemistry", "simulation", "javascript", "css", "html", "molecular", "visualization", "educational", "interactive", "computational", "science", "atoms", "electrons", "bonds", "geometry"],
		show: true
	},
	{
		title: "Match 3",
		date: "Sept 2025",
		timestamp: "2025-09-04T08:00:00Z",
		github: "https://github.com/wartets/Match3",
		description: "A classic gem-matching puzzle game with smooth animations and swap mechanics. Create lines of three or more matching colors to score points in this implementation.",
		longDescrition: "A classic gem-matching puzzle game with smooth animations and swap mechanics. Create lines of three or more matching colors to score points in this implementation. This project delivers a traditional Match 3 game experience with polished visual and interactive elements.",
		icon: "../img/Match3-card.png",
		image: "img/Match3-card.png",
		link: "https://wartets.github.io/Match3/",
		keywords: ["puzzle", "match-3", "game", "gem matching", "swap mechanics", "animations", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Labyrinthe",
		date: "Aug 2025",
		timestamp: "2025-08-19T08:00:00Z",
		github: "https://github.com/wartets/Labyrinthe",
		description: "This project explores maze solving through a highly customizable genetic/evolutionary algorithm approach. (fr)",
		longDescrition: "This project explores maze solving through a highly customizable genetic/evolutionary algorithm approach. It focuses on the use of algorithms to navigate and solve intricate mazes, offering a platform to visualize and understand evolutionary computation in action. (fr)",
		icon: "../img/Labyrinthe-card.png",
		image: "img/Labyrinthe-card.png",
		link: "https://wartets.github.io/Labyrinthe/",
		keywords: ["maze", "genetic algorithm", "evolutionary", "pathfinding", "simulation", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Autoroutes",
		date: "Aug 2025",
		timestamp: "2025-08-13T08:00:00Z",
		github: "https://github.com/wartets/Autoroutes",
		description: "A web simulation that procedurally generates a highway system. It uses simple rules to create a complex, winding road network, showcasing how basic algorithms can lead to intricate, emergent patterns. (fr)",
		longDescrition: "A web simulation that procedurally generates a highway system. It uses simple rules to create a complex, winding road network, showcasing how basic algorithms can lead to intricate, emergent patterns. (fr)",
		icon: "../img/Autoroutes-card.png",
		image: "img/Autoroutes-card.png",
		link: "https://wartets.github.io/Autoroutes/",
		keywords: ["procedural generation", "highway", "road network", "simulation", "emergence", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Mercury-Redstone",
		date: "Jul 2025",
		timestamp: "2025-07-07T08:00:00Z",
		github: "https://github.com/wartets/Mercury",
		description: "Simulation of the May 5, 1961 Mercury-Redstone mission. (fr)",
		longDescrition: "This project is a simulation of the May 5, 1961 Mercury-Redstone mission, the first United States human spaceflight piloted by astronaut Alan Shepard. The mission's primary objective was to demonstrate the astronaut's ability to withstand the high g-forces of launch and atmospheric re-entry during a 15-minute suborbital flight. The Mercury-Redstone Launch Vehicle was the first American crewed space booster, derived from the U.S. Army's Redstone ballistic missile. (fr)",
		icon: "../img/Mercury-card.png",
		image: "img/Mercury-card.png",
		link: "https://wartets.github.io/Mercury/",
		keywords: ["space", "simulation", "historical", "physics", "rocket", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Caustiques",
		date: "Jul 2025",
		timestamp: "2025-07-08T08:00:00Z",
		github: "https://github.com/wartets/Caustiques",
		description: "Simulation of caustic lines due to refraction of a corrugated glass base. (fr)",
		longDescrition: "This project simulates caustic lines formed by the refraction of light through a corrugated glass base. It's an exploration of optics, specifically focusing on how light bends and creates intricate patterns when passing through irregular surfaces. (fr)",
		icon: "../img/Caustiques-card.png",
		image: "img/Caustiques-card.png",
		link: "https://wartets.github.io/Caustiques/",
		keywords: ["optics", "simulation", "refraction", "caustics", "light", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Fractals",
		date: "Jul 2025",
		timestamp: "2025-07-11T08:00:00Z",
		github: "https://github.com/wartets/Fractals",
		description: "Generating fractal plant structures with affine transformations. (fr)",
		longDescrition: "This project focuses on generating fractal plant structures using affine transformations. Fractals are fascinating mathematical objects characterized by self-similarity, where patterns repeat at different scales. This project allows for the creation of complex, visually appealing fractal images based on simple mathematical formulas. (fr)",
		icon: "../img/Fractals-card.png",
		image: "img/Fractals-card.png",
		link: "https://wartets.github.io/Fractals/",
		keywords: ["fractals", "generative", "plants", "affine transformations", "L-system", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Lenia Web",
		date: "Jul 2025",
		timestamp: "2025-07-01T08:00:00Z",
		github: "https://github.com/wartets/Lenia-Web",
		description: "A dynamic web implementation of the Lenia system, modeling artificial organisms evolving via parameterized growth fields.",
		longDescrition: "A dynamic web implementation of the Lenia system, modeling artificial organisms evolving via parameterized growth fields. Lenia is a continuous cellular automaton, a generalization of Conway's Game of Life, known for producing a diverse range of complex and lifelike patterns.",
		icon: "../img/LeniaWeb-card.png",
		image: "img/LeniaWeb-card.png",
		link: "https://wartets.github.io/Lenia-Web/",
		keywords: ["cellular automata", "simulation", "emergence", "patterns", "Lenia", "Python", "css", "html"],
		show: true
	},
	{
		title: "Curve Fitting",
		date: "Jun 2025",
		timestamp: "2025-06-01T08:00:00Z",
		github: "https://github.com/wartets/Curve-Fitting",
		description: "This project illustrates thin-plate splines, a smooth surface interpolation technique used in geometry and machine learning.",
		longDescrition: "This project illustrates thin-plate splines, a smooth surface interpolation technique used in geometry and machine learning. Curve fitting is the process of constructing a mathematical function that best fits a series of data points, either through interpolation (exact fit) or smoothing (approximate fit). This project helps visualize how splines can be used to model data trends and create smooth curves.",
		icon: "../img/Curve-Fitting-card.png",
		image: "img/Curve-Fitting-card.png",
		link: "https://wartets.github.io/Curve-Fitting/",
		keywords: ["math", "interpolation", "splines", "visualization", "javascript", "css", "html"],
		show: false
	},
	{
		title: "Procedural Art Gen.",
		date: "May 2025",
		timestamp: "2025-05-01T08:00:00Z",
		github: "https://github.com/wartets/Procedural-Art",
		description: "A seed-based generative art system creating unique visual patterns. Explore geometric formations, organic fractals, and abstract compositions that remain reproducible.",
		longDescrition: "A seed-based generative art system creating unique visual patterns. Explore geometric formations, organic fractals, and abstract compositions that remain reproducible. This project demonstrates how algorithms can be used to create diverse and intricate art forms.",
		icon: "../img/Procedural-Art-card.png",
		image: "img/Procedural-Art-card.png",
		link: "https://wartets.github.io/Procedural-Art/",
		keywords: ["generative art", "procedural", "fractals", "patterns", "creative coding", "javascript", "css", "html"],
		show: true
	},
	[
		{
			title: "Space Trip Game 3D",
			date: "Apr 2025",
			timestamp: "2025-04-01T08:00:00Z",
			github: "https://github.com/wartets/Space-Trip-3D",
			description: "Survival game for a small ship in a swarm of asteroids, where you have to score as many points as possible by destroying them and staying alive as long as possible.",
			longDescrition: "Survival game for a small ship in a swarm of asteroids, where you have to score as many points as possible by destroying them and staying alive as long as possible. This 3D game challenges players with spatial navigation and combat in an asteroid field.",
			icon: "../img/Spaceship-card.png",
			image: "img/Spaceship-card.png",
			link: "https://wartets.github.io/Space-Trip-3D/",
			keywords: ["3D", "game", "space", "asteroids", "three.js", "survival", "javascript", "css", "html"],
			show: true
		},
		{
			title: "Space Trip Game 2D",
			date: "Mar 2025",
			timestamp: "2025-03-01T08:00:00Z",
			github: "https://github.com/wartets/Space-Trip-2D",
			description: "\"Simplified\" 2D version of the Space Trip game.",
			longDescrition: "\"Simplified\" 2D version of the Space Trip game. This project offers a two-dimensional take on the asteroid survival game, focusing on core mechanics and arcade-style gameplay.",
			icon: "../img/Space-Trip-2D.png",
			image: "img/Space-Trip-2D.png",
			link: "https://wartets.github.io/Space-Trip-2D/",
			keywords: ["2D", "game", "space", "asteroids", "canvas", "arcade", "javascript", "css", "html"],
			show: true
		}
	],
	{
		title: "Sudoku",
		date: "Feb 2025",
		timestamp: "2025-02-01T08:00:00Z",
		github: "https://github.com/wartets/Sudoku",
		description: "A customizable web-based Sudoku game that allows you to adjust both the grid size and difficulty level. It features real-time input validation, providing an interactive and engaging puzzle-solving experience.",
		longDescrition: "A customizable web-based Sudoku game that allows you to adjust both the grid size and difficulty level. It features real-time input validation, providing an interactive and engaging puzzle-solving experience. Sudoku is a logic-based number-placement puzzle where the objective is to fill a grid with digits so that each column, row, and subgrid contains all digits from 1 to 9.",
		icon: "../img/Sudoku-card.png",
		image: "img/Sudoku-card.png",
		link: "https://wartets.github.io/Sudoku/",
		keywords: ["puzzle", "game", "logic", "interactive", "validation", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Chess Game",
		date: "Jan 2025",
		timestamp: "2025-01-01T08:00:00Z",
		github: "https://github.com/wartets/Chess-Game",
		description: "An Interactive chess game, offering classic and random board setups. It allows custom piece placement, and personalized size grid.",
		longDescrition: "An interactive chess game, offering classic and random board setups. It allows custom piece placement and personalized grid size. The project implements the classic game of chess, allowing two players to compete with various customizable options.",
		icon: "../img/Chess-card.png",
		image: "img/Chess-card.png",
		link: "https://wartets.github.io/Chess-Game/",
		keywords: ["chess", "game", "strategy", "board game", "interactive", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Minesweeper",
		date: "Dec 2024",
		timestamp: "2024-12-01T08:00:00Z",
		github: "https://github.com/wartets/Demineur",
		description: "A simple mine-clearing game in javascript. Discover all the squares without touching a mine! Adjust the grid size and number of mines to personalize the experience.",
		longDescrition: "A simple mine-clearing game in javascript. Discover all the squares without touching a mine! Adjust the grid size and number of mines to personalize the experience. Minesweeper is a single-player puzzle game where the goal is to uncover all safe tiles and avoid hidden mines.",
		icon: "../img/Demineur-card.png",
		image: "img/Demineur-card.png",
		link: "https://wartets.github.io/Demineur/",
		keywords: ["game", "puzzle", "grid", "mines", "classic", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Julia-Set",
		date: "Nov 2024",
		timestamp: "2024-11-01T12:00:00Z",
		github: "https://github.com/wartets/Julia-Set",
		description: "Explore the beauty of Julia sets with interactive controls to adjust equations and rendering settings. Create custom stunning fractal visuals in \"real-time\" with a simple interface.",
		longDescrition: "Explore the beauty of Julia sets with interactive controls to adjust equations and rendering settings. Create custom stunning fractal visuals in \"real-time\" with a simple interface. This project delves into the mathematical properties of Julia sets, which are fascinating fractals related to the Mandelbrot set.",
		icon: "../img/JuilaSet-card.png",
		image: "img/JuilaSet-card.png",
		link: "https://wartets.github.io/Julia-Set/",
		keywords: ["fractals", "math", "visualization", "interactive", "complex numbers", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Bird-cloud",
		date: "Nov 2024",
		timestamp: "2024-11-01T08:00:00Z",
		github: "https://github.com/wartets/Bird-cloud",
		description: "An interactive simulation of flocking behavior in birds, based on the Boids model. Adjust parameters like speed, vision radius, and randomness to see how individual rules create collective patterns.",
		longDescrition: "An interactive simulation of flocking behavior in birds, based on the Boids model. Adjust parameters like speed, vision radius, and randomness to see how individual rules create collective patterns. This project showcases emergent behavior in artificial life, where simple rules lead to complex, coordinated movements.",
		icon: "../img/BirdCloud-card.png",
		image: "img/BirdCloud-card.png",
		link: "https://wartets.github.io/Bird-cloud/",
		keywords: ["simulation", "boids", "flocking", "emergence", "interactive", "javascript", "css", "html"],
		show: true
	},
	{
		title: "N-Body-Problem",
		date: "Oct 2024",
		timestamp: "2024-10-01T08:00:00Z",
		github: "https://github.com/wartets/N-Body-Problem",
		description: "A physics simulation of an N-body system with gravity, collisions, and electromagnetism. Customize object properties like mass, charge, and position to observe how forces shape their motion.",
		longDescrition: "A physics simulation of an N-body system with gravity, collisions, and electromagnetism. Customize object properties like mass, charge, and position to observe how forces shape their motion. The N-body problem in physics involves predicting the individual motions of celestial objects interacting gravitationally.",
		icon: "../img/NBodyProblem-card.png",
		image: "img/NBodyProblem-card.png",
		link: "https://wartets.github.io/N-Body-Problem/",
		keywords: ["physics", "simulation", "gravity", "electromagnetism", "n-body", "javascript", "css", "html"],
		show: true
	},
	{
		title: "Lenia-Simulation",
		date: "Jun 2024",
		timestamp: "2024-06-01T08:00:00Z",
		github: "https://github.com/wartets/Lenia-Simulation",
		description: "Discover Lenia, a continuous cellular automaton that extends Conway's Game of Life. Explore lifelike, emergent patterns in a world of smooth transitions and endless complexity.",
		longDescrition: "Discover Lenia, a continuous cellular automaton that extends Conway's Game of Life. Explore lifelike, emergent patterns in a world of smooth transitions and endless complexity. Lenia models artificial organisms evolving via parameterized growth fields.",
		icon: "../img/LeniaSimulation-card.png",
		image: "img/LeniaSimulation-card.png",
		link: "https://wartets.github.io/Lenia-Simulation/",
		keywords: ["cellular automata", "simulation", "emergence", "patterns", "Lenia", "Python", "css", "html"],
		show: true
	},
	{
		title: "Solar-System",
		date: "May 2023",
		timestamp: "2024-05-01T08:00:00Z",
		github: "https://github.com/wartets/SolarSystem",
		description: "A 3D solar system visualization. Interact with the planets and their orbits in a dynamic and immersive interface.",
		longDescrition: "A 3D solar system visualization. Interact with the planets and their orbits in a dynamic and immersive interface. This project aims to help users learn more about space and the planets within our solar system, demonstrating their arrangement and unique characteristics.",
		icon: "../img/SolarSystem-card.png",
		image: "img/SolarSystem-card.png",
		link: "https://wartets.github.io/SolarSystem/",
		keywords: ["3D", "space", "simulation", "planets", "orbits", "Java", "GeogebraScript", "GeoGebra", "css", "html"],
		show: true
	},
	[
		{
			title: "My Music (SoundCloud)",
			date: "",
			timestamp: "",
			github: "",
			description: "I create electronic, ambient, funky, and drumcore music. I focus on improving my skills and exploring new sounds. Check out my tracks and enjoy the beats!",
			longDescrition: "I create electronic, ambient, funky, and drumcore music. I focus on improving my skills and exploring new sounds. Check out my tracks and enjoy the beats!",
			icon: "../img/Soundcloud-card.jpg",
			image: "img/Soundcloud-card.jpg",
			link: "https://soundcloud.com/wartets",
			keywords: ["music", "electronic", "ambient", "soundcloud", "creative"],
			show: true
		},
		{
			title: "My Music (YouTube)",
			date: "",
			timestamp: "",
			github: "",
			description: "Explore my music projects on YouTube.",
			longDescrition: "Explore my music projects on YouTube.",
			icon: "",
			image: "",
			link: "https://www.youtube.com/@Wartets",
			keywords: ["music", "youtube", "electronic", "drumcore", "creative"],
			show: true
		}
	]
];