window.libraryData = {
	categories: [
		{ id: 1, name: "Physics" },
		{ id: 2, name: "Mathematics" },
		{ id: 3, name: "Computer Science" },
		{ id: 4, name: "Personal Notes" }
	],
	authors: [
		{ id: "cbr", name: "Colin Bossu Réaubourg" }
	],
	documents: [
		{
			id: "doc-01",
			title: "Introduction à la Physique Quantique",
			description: "Notes de cours magistral de troisième année de licence.",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Cours_Quantique_1.pdf",
			categoryId: 1,
			authorIds: ["cbr"],
			tags: ["physics", "quantum", "university", "lecture", "lesson"],
			timestamp: "2025-12-13T00:00:00Z",
		},
		{
			id: "doc-02",
			title: "Mathématiques 5 - Cours",
			description: "Écriture tensorielle, Analyse complexe, Séries de Fourier et Équations différentielles.",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Cours_Mathématiques_5.pdf",
			categoryId: 2,
			authorIds: ["cbr"],
			tags: ["mathematics", "university", "lecture", "lesson"],
			timestamp: "2025-12-08T00:00:00Z",
		},
		{
			id: "doc-03",
			title: "Rapport de physique expérimentale - Etude du lasso",
			description: "Étude expérimentale de la bifurcation supercritique d’un anneau en rotation : effets de géométrie finie et imperfections.",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Rapport_Final_Physique_Expérimentale.pdf",
			categoryId: 1,
			authorIds: ["cbr"],
			tags: ["physics", "experimental", "university", "lecture"],
			timestamp: "2025-12-07T00:00:00Z",
		},
		{
			id: "doc-04",
			title: "Résolution de l'équation de Schrödinger pour un potentiel périodique fini",
			description: "",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Résolution_eqShrod_period_fini.pdf",
			categoryId: 1,
			authorIds: ["cbr"],
			tags: ["physics", "quantum", "exercise"],
			timestamp: "2025-10-16T00:00:00Z",
		},
		{
			id: "doc-05",
			title: "Probabilités et Lancer de Dés",
			description: "Calcul des probabilités associées aux sommes obtenues lors de lancers de dés.",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Lancé_de_dés.pdf",
			categoryId: 2,
			authorIds: ["cbr"],
			tags: ["mathematics", "exercise", "probabilities"],
			timestamp: "2025-11-07T00:00:00Z",
		},
		{
			id: "doc-06",
			title: "Informatique Quantique avec Qiskit",
			description: "Traité sur l'information quantique avec Qiskit",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Informatique_Quantique_avec_Qiskit.pdf",
			categoryId: 1,
			authorIds: ["cbr"],
			tags: ["physics", "quantum", "lesson", "computer"],
			timestamp: "2025-09-29T00:00:00Z",
		},
		{
			id: "doc-07",
			title: "Optique et électromagnétisme - Cours",
			description: "Optique ondulatoire et électromagnétisme dans les milieu.",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Cours_OOEM.pdf",
			categoryId: 1,
			authorIds: ["cbr"],
			tags: ["physics", "optics", "university", "lecture", "lesson"],
			timestamp: "2025-09-25T00:00:00Z",
		},
		{
			id: "doc-08",
			title: "Quelques formules mathématiques pour la physique",
			description: "Formules mathématiques couramment utilisées en physique, présentées de manière concise comme référence analytique.",
			filePath: "https://wartets.github.io/Wartets/lib/assets/Quelques_formules_mathématiques_pour_la_physique.pdf",
			categoryId: 2,
			authorIds: ["cbr"],
			tags: ["physics", "mathematics"],
			timestamp: "2025-08-10T00:00:00Z",
		},
		{
			id: "doc-09",
			title: "Théorie Algébrique des Unités, Constantes et Normalisation Physique",
			description: "Formalisme mathématique, métrologie et implémentation numérique de la théroie des unitées",
			filePath: "https://wartets.github.io/Wartets/lib/assets/theorie_algebrique_unites.pdf",
			categoryId: 1,
			authorIds: ["cbr"],
			tags: ["physics", "mathematics", "computer science"],
			timestamp: "2025-12-09T00:00:00Z",
		},
	]
};